events {
    worker_connections 1024;
}

http {
    upstream backend {
        # Docker DNS will automatically resolve this to the 2 web replicas
        server web:8000;
    }

    server {
        listen 80;
        
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        # Route all traffic to the backend instances
        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
